// Code generated by "callbackgen -type VR"; DO NOT EDIT.

package indicator

import ()

func (vr *VR) OnUpdate(cb func(value float64)) {
	vr.UpdateCallbacks = append(vr.UpdateCallbacks, cb)
}

func (vr *VR) EmitUpdate(value float64) {
	for _, cb := range vr.UpdateCallbacks {
		cb(value)
	}
}
